# Source: vault/templates/injector-mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
webhooks:
  - name: vault.hashicorp.com
    sideEffects: None
    admissionReviewVersions:
    - "v1beta1"
    - "v1"
    clientConfig:
      service:
        name: vault-agent-injector-svc
        namespace: spi
        path: "/mutate"
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNTRENDQWU2Z0F3SUJBZ0lVWE1IdXNubmhGRWYwcHNxaUJMN2lsa0xud3R3d0NnWUlLb1pJemowRUF3SXcKR2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUI0WERUSXhNVEV4TWpFME16SXdORm9YRFRNeApNVEV4TURFME16TXdORm93R2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUZrd0V3WUhLb1pJCnpqMENBUVlJS29aSXpqMERBUWNEUWdBRWVCbyt3MVBKTUhTakJSNU9pUU1Wc2g3QS9wVEFsTHpYTVdiL24vYUoKMkEwZXh0WnpxaFVyQmNTcE5PVHFMd3ZCczNzeFg3YlhhcFhaL3ZSZ2dyVk9nYU9DQVJBd2dnRU1NQTRHQTFVZApEd0VCL3dRRUF3SUNoREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvCk1HZ0dBMVVkRGdSaEJGOWlaRG93WVRwbE9EcGhZVHBqTkRwallUbzJNanBoTURwaFpEb3pOanBtWXpveFpqcGkKWlRwaE5qbzJZVG94TkRvelpqbzVORG8xTURwaU56cGhaRG8wWmpvellqbzNaanBoTURvNFlqb3pNRG8wTlRwawpNRHBqTWpvd05EcGlZakJxQmdOVkhTTUVZekJoZ0Y5aVpEb3dZVHBsT0RwaFlUcGpORHBqWVRvMk1qcGhNRHBoClpEb3pOanBtWXpveFpqcGlaVHBoTmpvMllUb3hORG96WmpvNU5EbzFNRHBpTnpwaFpEbzBaam96WWpvM1pqcGgKTURvNFlqb3pNRG8wTlRwa01EcGpNam93TkRwaVlqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQmxCOGZOcTlOdgp2NmI2TCtWSDljVE1pUnM3Q2NtMTRtR1ZCQjk0eUVWblBnSWhBTTBjcEtTUWpBQXRmVC9leVo5V01LVWVtdjNVCk9IZWxhTVJyMlFKOTYyUVIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
