apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service-provider-integration-api
    app.kubernetes.io/version: 0.1.0
  name: service-provider-integration-api
spec:
  ports:
    - name: http
      nodePort: 31441
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: service-provider-integration-api
    app.kubernetes.io/version: 0.1.0
  type: NodePort