apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spi-operator
  namespace: spi
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: spi-service
  source: spi-operator-catalog
  sourceNamespace: spi
  startingCSV: service-provider-integration-operator.v0.1.0